#端口号配置
server:
  port: 8002

#spring相关配置
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

#mybatis相关配置
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: com.sun.cloud.pojo
  configuration:
    map-underscore-to-camel-case: true

#mybatis日志打印
logging.level.com.sun.cloud.mapper: debug

#Eureka Client相关配置
eureka:
  instance:
    #eureka web端显示主机名称
    instance-id: payment8002
    #显示ip地址
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#      defaultZone: http://localhost:7001/eureka #单机版